### ISSUE TITLE
TSseq.py outputs a non conformat csv

### ISSUE THREAD

**Issue by StuntsPT** [CoBiG2/cobig_misc_scripts#4]
The csv outputted by this script splits the first column from the rest of the file with a tab character (\t), whereas the rest of the columns are split with "whitespace" ("\s").
The file should either be fully split with tabs, or with whitespace, but not both.

**Comment by StuntsPT** [comment]
Nevermind, I just fixed it. =-)

**Comment by LoboGalhardo** [comment]
Thank you! :D

**Comment by StuntsPT** [comment]
No problem.
Cheers!
